;;; real-mono-themes.el --- Real monochromatic color themes -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Qingsong Liao

;; Author: Qingsong Liao <llqingsong@qq.com>
;; Maintainer: Qingsong Liao <llqingsong@qq.com>
;; URL: https://github.com/qingsongliao/real-mono-themes
;; Created: 15th Nov 2025
;; Version: 1.0.0
;; Keywords: faces
;; Package-Requires: ((emacs "24"))

;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published
;; by the Free Software Foundation, either version 3 of the License,
;; or (at your option) any later version.

;; This file is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this file.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; A suite of real monochrome Emacs themes

;;; Code:

(defconst real-mono-themes-colors
  '((eink . ((background . "#ffffff")
	          (foreground . "#000000")))

    (dark . ((background . "#000000")
	          (foreground . "#ffffff")))

    (girl .  ((background . "#ffaeb9")
	          (foreground . "#8b636c")))

    (old . ((background . "#050505")
	        (foreground . "#7cfc00")))

    (sea . ((background . "#20b2aa")
	        (foreground . "#f4a460")))))

(defmacro real-mono-themes--variant-with-colors (variant &rest body)
  "Execute BODY in a scope where the different colors for given VARIANT is bound."
  `(let* ((colors (or (cdr (assoc ,variant real-mono-themes-colors))
		              (error "No such theme variant")))
	      (background (cdr (assoc 'background colors)))
	      (foreground (cdr (assoc 'foreground colors))))
     ,@body))

(defmacro real-mono-themes--faces-spec ()
  "Provide the faces specification."
  (quote
   (mapcar
    (lambda (entry) (list (car entry) `((t ,@(cdr entry)))))
    `(
      (ansi-color-bright-cyan (:background "blue" :foreground "blue"))
      (ansi-color-bright-green (:background "sea green" :foreground "sea green"))
      (ansi-color-bright-yellow (:background "saddle brown" :foreground "saddle brown"))
      (ansi-color-cyan (:background "medium blue" :foreground "medium blue"))
      (ansi-color-green (:background "green" :foreground "green"))
      (ansi-color-underline ())
      (ansi-color-yellow (:background "red" :foreground "red"))
      (avy-lead-face (:inverse-video t :inherit (bold)))
      (avy-lead-face-0 (:inverse-video t))
      (avy-lead-face-1 (:inverse-video t))
      (avy-lead-face-2 (:inverse-video t))
      (bold (:weight bold))
      (bookmark-face ())
      (button (:box (:line-width (1 . -1) :color ,foreground :style released-button)))
      (company-echo-common ())
      (company-scrollbar-bg ())
      (company-scrollbar-fg ())
      (company-tooltip ())
      (company-tooltip-annotation ( :italic t))
      (company-tooltip-annotation-selection (:italic t))
      (company-tooltip-common (:bold t))
      (company-tooltip-common-selection (:bold t))
      (company-tooltip-selection ())
      (company-tooltip-selection ())
      (compilation-error (:inherit error))
      (compilation-info ())
      (compilation-mode-line-exit ())
      (compilation-mode-line-fail (:inherit error))
      (compilation-mode-line-run (:inherit warning))
      (compilation-warning (:inherit warning))
      (completions-common-part ())
      (completions-highlight (:inherit highlight))
      (consult-async-finished (:inherit success))
      (consult-separator ())
      (corfu-annotations ())
      (corfu-bar (:inverse-video t))
      (corfu-border (:inverse-video t))
      (corfu-current (:underline t))
      (corfu-default ())
      (custom-button (:inherit button))
      (custom-button-mouse (:inherit button))
      (custom-button-pressed (:inherit button))
      (custom-changed (:inverse-video t))
      (custom-comment ())
      (custom-invalid (:inverse-video t))
      (custom-link (:inherit (link)))
      (custom-rogue (:inverse-video t))
      (custom-state ())
      (custom-variable-tag (:inherit bold))
      (default (:background ,background :foreground ,foreground))
      (diary ())
      (diff-added ())
      (diff-error (:inherit (pyim-page bold error)))
      (diff-file-header :inherit bold)
      (diff-function (:inherit (bold)))
      (diff-header (:inherit bold))
      (diff-index (:inherit bold))
      (diff-indicator-added ())
      (diff-indicator-removed ())
      (diff-refine-added (:underline (:color foreground-color :style dots :position ()) :weight bold))
      (diff-refine-changed ())
      (diff-refine-removed (:inherit region))
      (diff-removed ())
      (dired-async-failures (:inherit error))
      (dired-async-message (:inherit success))
      (dired-async-mode-message (:inherit warning))
      (dired-broken-symlink (:inverse-video t :inherit (bold link)))
      (dired-directory (:inherit bold))
      (dired-mark (:inverse-video t))
      (dired-marked ())
      (dired-subtree-depth-1-face ())
      (dired-subtree-depth-2-face ())
      (dired-subtree-depth-3-face ())
      (dired-subtree-depth-4-face ())
      (eglot-highlight-symbol-face ())
      (elisp-shorthand-font-lock-face ())
      (elisp-unknown-call ())
      (envrc-mode-line-error-face (:inherit error))
      (envrc-mode-line-none-face ())
      (envrc-mode-line-on-face ())
      (epa-mark (:inherit (button bold)))
      (error ())
      (escape-glyph ())
      (eshell-ls-archive (:inherit eshell-ls-unreadable))
      (eshell-ls-backup (:inherit eshell-ls-unreadable))
      (eshell-ls-clutter (:inherit eshell-ls-unreadable))
      (eshell-ls-directory (:bold t))
      (eshell-ls-executable (:inherit eshell-ls-unreadable))
      (eshell-ls-missing (:inherit eshell-ls-unreadable))
      (eshell-ls-product (:inherit eshell-ls-unreadable))
      (eshell-ls-readonly (:inherit eshell-ls-unreadable))
      (eshell-ls-special (:inherit eshell-ls-unreadable))
      (eshell-ls-symlink (:inherit eshell-ls-unreadable))
      (eshell-prompt (:bold t))
      (eshell-prompt (:inherit bold))
      (eww-form-checkbox (:inherit (box)))
      (eww-form-file (:inherit (box)))
      (eww-form-select (:inherit (box)))
      (eww-form-submit (:inherit (box)))
      (eww-form-text (:inherit (box)))
      (eww-form-textarea (:inherit (box)))
      (eww-valid-certificate (:weight bold))
      (fixed-pitch ())
      (fixed-pitch-serif ())
      (flycheck-error (:inherit error))
      (flycheck-warning (:inherit warning))
      (flymake-error ())
      (flymake-note ())
      (flymake-warning ())
      (font-lock-bracket-face ())
      (font-lock-builtin-face ())
      (font-lock-comment-delimiter-face ())
      (font-lock-comment-face ())
      (font-lock-constant-face ())
      (font-lock-delimiter-face ())
      (font-lock-doc-face ())
      (font-lock-doc-markup-face ())
      (font-lock-escape-face ())
      (font-lock-function-call-face ())
      (font-lock-function-name-face ())
      (font-lock-keyword-face ())
      (font-lock-misc-punctuation-face ())
      (font-lock-negation-char-face ())
      (font-lock-number-face ())
      (font-lock-operator-face ())
      (font-lock-preprocessor-face ())
      (font-lock-property-name-face ())
      (font-lock-property-use-face ())
      (font-lock-punctuation-face ())
      (font-lock-reference-face ())
      (font-lock-regexp-grouping-backslash ())
      (font-lock-regexp-grouping-construct ())
      (font-lock-string-face ())
      (font-lock-type-face ())
      (font-lock-variable-name-face (:underline ()))
      (font-lock-variable-use-face ())
      (font-lock-warning-face ())
      (forge-dimmed (:inherit (magit-dimmed)))
      (forge-pullreq-merged ())
      (fringe ())
      (git-gutter:added ())
      (git-gutter:deleted ())
      (git-gutter:modified ())
      (gnus-group-mail-1 (:weight bold))
      (gnus-group-mail-2 (:weight bold))
      (gnus-group-mail-3 (:weight bold))
      (gnus-group-mail-4 (:weight bold))
      (gnus-group-news-1 (:weight bold))
      (gnus-group-news-2 (:weight bold))
      (gnus-group-news-3 (:weight bold))
      (gnus-group-news-4 (:weight bold))
      (gnus-header-content ())
      (gnus-header-from ())
      (gnus-header-name ())
      (gnus-header-subject ())
      (gnus-splash ())
      (gnus-summary-high-undownloaded (:weight bold))
      (go-coverage-covered ())
      (header-line ())
      (help-key-binding (:inherit (fixed-pitch button)))
      (highlight (:weight bold))
      (hl-todo (:weight bold))
      (holiday ())
      (homoglyph ())
      (icon-button (:inherit (button icon)))
      (ido-first-match ())
      (ido-first-match (:bold t))
      (ido-only-match ())
      (ido-only-match (:bold t))
      (ido-subdir ())
      (ido-subdir (:italic t))
      (ido-vertical-match-face (:bold t))
      (ido-virtual ())
      (iedit-occurrence ())
      (info-index-match ())
      (info-menu-header (:inherit variable-pitch))
      (info-menu-star ())
      (info-node ())
      (info-title-1 ())
      (info-title-2 ())
      (info-title-3 ())
      (info-title-4 (:inherit variable-pitch))
      (info-xref ())
      (info-xref-visited ())
      (isearch ())
      (isearch-fail ())
      (italic (:slant italic))
      (lazy-highlight (:weight bold))
      (link ())
      (link-visited (:inherit link))
      (magit-bisect-bad (:inherit (italic)))
      (magit-bisect-good (:inherit bold))
      (magit-bisect-skip ())
      (magit-blame-dimmed (:inherit (magit-dimmed)))
      (magit-blame-heading (:inherit button))
      (magit-blame-highlight ())
      (magit-blame-margin (:inherit (warning)))
      (magit-branch-current (:weight bold :inherit italic))
      (magit-branch-local (:inherit (italic)))
      (magit-branch-remote (:inherit bold))
      (magit-cherry-equivalent ())
      (magit-cherry-unmatched (:inherit (italic)))
      (magit-diff-added ())
      (magit-diff-added-highlight ())
      (magit-diff-base ())
      (magit-diff-base-highlight (:inherit (italic)))
      (magit-diff-context ())
      (magit-diff-context-highlight ())
      (magit-diff-file-heading-selection ())
      (magit-diff-hunk-heading (:inherit (italic)))
      (magit-diff-hunk-heading-highlight (:inherit italic))
      (magit-diff-hunk-heading-selection ())
      (magit-diff-lines-heading (:inherit button))
      (magit-diff-refine-added (:inherit diff-refine-added))
      (magit-diff-refine-removed (:inherit diff-refine-removed))
      (magit-diff-removed ())
      (magit-diff-removed-highlight ())
      (magit-diffstat-added (:inherit bold))
      (magit-diffstat-removed ())
      (magit-dimmed (:weight light))
      (magit-hash (:inherit (italic)))
      (magit-header (:inherit bold))
      (magit-item-highlight (:inherit bold))
      (magit-item-mark ())
      (magit-log-author (:inherit bold))
      (magit-log-date ())
      (magit-log-graph ())
      (magit-process-ng (:inherit (bold button)))
      (magit-process-ok (:inherit (bold button)))
      (magit-reflog-amend (:inherit (italic)))
      (magit-reflog-checkout (:inherit bold))
      (magit-reflog-cherry-pick ())
      (magit-reflog-commit (:inherit bold))
      (magit-reflog-merge (:inherit (italic bold)))
      (magit-reflog-other ())
      (magit-reflog-rebase (:inherit (italic)))
      (magit-reflog-remote (:inherit bold))
      (magit-reflog-reset ())
      (magit-refname ())
      (magit-section-heading (:inherit bold))
      (magit-section-heading-selection ())
      (magit-section-highlight ())
      (magit-sequence-drop (:inherit (italic)))
      (magit-sequence-head (:inherit bold))
      (magit-sequence-part (:inherit (italic)))
      (magit-sequence-stop (:inherit button))
      (magit-signature-bad (:inherit (italic bold)))
      (magit-signature-error (:inherit error))
      (magit-signature-expired ())
      (magit-signature-good (:inherit bold))
      (magit-signature-revoked (:inherit (italic)))
      (magit-signature-untrusted ())
      (magit-tag (:inherit (button bold)))
      (marginalia-documentation ())
      (markdown-highlighting-face ())
      (match (:inherit bold))
      (message-header-name ())
      (message-header-other ())
      (message-header-to (:inherit bold))
      (message-mml ())
      (minibuffer-depth-indicator ())
      (minibuffer-nonselected (:inherit bold))
      (minibuffer-prompt ())
      (mmm-default-submode-face ())
      (mode-line ())
      (mode-line-buffer (:inherit bold))
      (mode-line-buffer-id ())
      (mode-line-emphasis ())
      (mode-line-highlight ())
      (mode-line-inactive ())
      (mode-line-minor-mode (:weight light))
      (next-error (:inherit error))
      (nlinum-relative-current-face (:inherit normal :weight bold))
      (orderless-match-face-0 (:underline t))
      (orderless-match-face-1 (:underline t))
      (orderless-match-face-2 (:underline t))
      (orderless-match-face-3 (:underline t))
      (org-agenda-date (:height 1.2))
      (org-agenda-date-today (:weight bold :height 1.4))
      (org-agenda-date-weekend (:weight regular))
      (org-agenda-structure ())
      (org-block ())
      (org-clock-overlay ())
      (org-column (:inverse-video t))
      (org-column-title (:inverse-video t :weight bold))
      (org-date () :underline)
      (org-dispatcher-highlight (:weight bold))
      (org-done ())
      (org-headline-done ())
      (org-headline-todo ())
      (org-level-1 ())
      (org-level-2 ())
      (org-level-3 ())
      (org-level-4 ())
      (org-level-5 ())
      (org-level-6 ())
      (org-mode-line-clock-overrun (:inverse-video t))
      (org-quote (:inverse-video t :inherit intalic))
      (org-scheduled ())
      (org-scheduled-previously ())
      (org-scheduled-today ())
      (org-sexp-date ())
      (org-special-keyword ())
      (org-table ( :height 0.8))
      (org-table-header ())
      (org-todo ())
      (org-verbatim (:weight bold))
      (org-verse (:inherit italic))
      (package-mark-delete-line (:inherit diff-refine-removed))
      (package-mark-install-line (:underline t))
      (pdf-links-read-link (:inverse-video t ink))
      (pyim-page (:inverse-video t))
      (pyim-page-border ())
      (pyim-page-border (:inverse-video t))
      (pyim-page-selection ())
      (pyim-preview-face ())
      (query-replace ())
      (region (:underline (:color foreground-color :style double-line :position ())))
      (secondary-selection (:inherit diff-refine-removed))
      (sh-heredoc ())
      (sh-quoted-exec ())
      (shadow ())
      (show-paren-match ())
      (show-paren-match-expression ())
      (show-paren-mismatch ())
      (shr-abbreviation ())
      (shr-code ())
      (shr-h1 ())
      (shr-h2 ())
      (shr-h3 ())
      (shr-h4 ())
      (shr-h5 ())
      (shr-h6 ())
      (shr-link (:inherit (link)))
      (shr-mark ())
      (shr-selected-link ())
      (shr-sliced-image ())
      (shr-strike-through ())
      (shr-sup ())
      (shr-text ())
      (success (:inherit bold))
      (tab-bar (:inherit variable-pitch))
      (tab-bar-tab-highlight (:inherit button))
      (tab-bar-tab-inactive ())
      (tab-bar-tab-ungrouped ())
      (tab-line (:inherit variable-pitch))
      (tab-line-highlight (:inherit button))
      (tldr-code-block ())
      (tldr-command-argument ())
      (tldr-command-itself ())
      (tldr-description ())
      (tldr-introduction ())
      (tldr-title (:inherit bold))
      (tool-bar (:inherit button))
      (tooltip (:inherit variable-pitch))
      (trailing-whitespace (:inverse-video t))
      (transient-argument (:weight bold))
      (transient-disabled-suffix ())
      (transient-enabled-suffix (:inherit bold))
      (transient-heading ())
      (transient-key ())
      (transient-key-exit ())
      (transient-key-noop ())
      (transient-key-recurse ())
      (transient-key-return ())
      (transient-key-stack ())
      (transient-key-stack ())
      (transient-key-stay ())
      (transient-mismatched-key (:underline t))
      (transient-nonstandard-key (:underline t))
      (transient-pink (:weight bold))
      (transient-purple (:weight bold))
      (transient-red (:weight bold))
      (transient-teal (:weight bold))
      (transient-unreachable ())
      (transient-unreachable-key ())
      (transient-value ())
      (transient-value ())
      (variable-pitch ())
      (vertico-current (:inherit italic))
      (warning ())
      (wgrep-delete-face (:inherit diff-refine-removed))
      (wgrep-done-face ())
      (wgrep-face ())
      (wgrep-file-face (:inverse-video t))
      (wgrep-reject-face (:underline (:color foreground-color :style wave :position ()) :weight bold))
      (whitespace-line ())
      (widget-field (:inherit button))
      (widget-single-line-field ())
      (window-divider ())
      (window-divider-first-pixel ())
      ))))


(defun real-mono-themes--variant-name (variant)
  "Create symbol for color theme variant VARIANT."
  (intern (format "real-mono-%s" (symbol-name variant))))

(defmacro real-mono-themes--define-theme (variant)
  "Define a theme for the real-mono variant VARIANT."
  (let ((name (real-mono-themes--variant-name variant))
        (doc (format "real mono theme (%s version)" variant)))
    `(progn
       (deftheme ,name ,doc)
       (put ',name 'theme-immediate t)
       (real-mono-themes--variant-with-colors
        ',variant
        (apply 'custom-theme-set-faces ',name
               (real-mono-themes--faces-spec)))
       (provide-theme ',name))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
	           (file-name-as-directory (file-name-directory load-file-name))))

(provide 'real-mono-themes)

;;; real-mono-themes.el ends here
